### ISSUE TITLE
cannot build source 

### ISSUE THREAD

**Issue by ahadel** [cpboyd/simply-dicom#1]
Hello 
thank you for your work , it helped me , howerver i cant build your source due to missing file DcmViewer.java , can u help me in it ?

regards

**Comment by andremacpereira** [comment]
I've got the same issue. Where's DcmViewer.java?

**Comment by ahadel** [comment]
i think he intended this, not forget  , i have to rewrite it

**Comment by RajaVenkatesh-Sakhinala** [comment]
Hi,

I too unable to load the project because of errors with DCM Viewer. Seems the library project is missing in this. Can you please share the library project.

Thanks in advance.

**Comment by binhbinh** [comment]
please help me  DcmViewer.java !!!

**Comment by cpboyd** [comment]
This is resolved in the latest commits that I've pushed.
