### ISSUE TITLE
Miss OpenCV Lib

### ISSUE THREAD

**Issue by benntqoo** [cpboyd/simply-dicom#5]
Miss OpenCV library

**Comment by cpboyd** [comment]
You need to download the [OpenCV SDK](https://opencv.org/releases/).
I've only used OpenCV v3, so I'm not sure if v4 will work.

After doing so, you need to adjust this line:

https://github.com/cpboyd/simply-dicom/blob/5de39ddd6dc0fb0595e9051c066aa3809361f4b7/settings.gradle#L4

**Comment by benntqoo** [comment]
thanks, i got it :D
